pipeline {
	agent any	
	
	stages{
		stage('Checkout Code'){
			steps{
				checkout scm
				}
			}
	
	stage('Build'){
		steps{
			sh "cd Calculator-project/Calculator-project && mvn clean install -Dmaven.test.skip=true"
		}
	}
	
	stage('Archive Artifact'){
		steps{
		archiveArtifacts artifacts:'target/*.jar'
		}
	}
	
	stage('deployment'){
		steps{
		deploy adapters: [tomcat9(url: 'http://34.204.10.128:8080/', 
                              credentialsId: 'tomcat-cred')], 
                     war: 'target/*.jar',
                     contextPath: 'app'
		}
		
	}
    }
}
